# Generated by Django 3.1.5 on 2021-02-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='full_name',
            field=models.CharField(default='<django.db.models.fields.CharField> <django.db.models.fields.CharField>', max_length=512),
        ),
        migrations.AddField(
            model_name='player',
            name='number_of_legs_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='number_of_legs_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='number_of_matches_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='number_of_sets_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='number_of_sets_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='num_legs_complete',
            field=models.IntegerField(default=0),
        ),
    ]
